In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [2]:
import keras
from keras.layers import Dense
from keras.models import Sequential

In [3]:
dataset= pd.read_csv('binary_log.csv')

In [4]:
dataset

SAT Admitted  Gender
0    1363       No    Male
1    1792      Yes  Female
2    1954      Yes  Female
3    1653       No    Male
4    1593       No    Male
..    ...      ...     ...
163  1722      Yes  Female
164  1750      Yes    Male
165  1555       No    Male
166  1524       No    Male
167  1461       No    Male

[168 rows x 3 columns]

In [5]:
dataset['Admitted']= dataset['Admitted'].map({'Yes':1,'No':0})
dataset['Gender']= dataset['Gender'].map({'Female':1,'Male':0})

In [6]:
dataset

SAT  Admitted  Gender
0    1363         0       0
1    1792         1       1
2    1954         1       1
3    1653         0       0
4    1593         0       0
..    ...       ...     ...
163  1722         1       1
164  1750         1       0
165  1555         0       0
166  1524         0       0
167  1461         0       0

[168 rows x 3 columns]

In [7]:
x= dataset.iloc[:,[0,2]].values

In [8]:
x

array([[1363,    0],
       [1792,    1],
       [1954,    1],
       [1653,    0],
       [1593,    0],
       [1755,    1],
       [1775,    1],
       [1887,    1],
       [1893,    1],
       [1580,    0],
       [1857,    1],
       [1880,    1],
       [1664,    1],
       [1364,    0],
       [1693,    0],
       [1850,    1],
       [1633,    0],
       [1634,    0],
       [1636,    1],
       [1855,    1],
       [1987,    1],
       [1997,    0],
       [1422,    1],
       [1508,    1],
       [1720,    1],
       [1879,    0],
       [1634,    1],
       [1802,    0],
       [1849,    1],
       [1764,    1],
       [1460,    0],
       [1675,    1],
       [1656,    0],
       [2020,    0],
       [1850,    0],
       [1865,    0],
       [1664,    0],
       [1872,    1],
       [1654,    0],
       [1393,    1],
       [1587,    0],
       [1631,    1],
       [1931,    0],
       [1370,    0],
       [1810,    0],
       [1414,    0],
       [1761,    1],
       [1477,

In [9]:
y= dataset.iloc[:,1].values

In [10]:
y

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
x_train.shape

(134, 2)

In [14]:
x_test.shape

(34, 2)

In [15]:
import tensorflow as tf

In [16]:
model= Sequential([
    Dense(10,activation=tf.nn.relu,input_shape=[2],name='hidden_layer_0'),
    Dense(10,activation=tf.nn.relu,name='hidden_layer_1'),
    Dense(10,activation=tf.nn.relu,name='hidden_layer_2'),
    Dense(1,activation=tf.nn.sigmoid,name='output_layer')
])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hidden_layer_0 (Dense)       (None, 10)                30        
_________________________________________________________________
hidden_layer_1 (Dense)       (None, 10)                110       
_________________________________________________________________
hidden_layer_2 (Dense)       (None, 10)                110       
_________________________________________________________________
output_layer (Dense)         (None, 1)                 11        
Total params: 261
Trainable params: 261
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss='binary_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [19]:
model.fit(x_train,y_train,epochs=500)

Epoch 1/500
5/5 [==============================] - 1s 2ms/step - loss: 42.7187 - accuracy: 0.5597
Epoch 2/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6928 - accuracy: 0.5597
Epoch 3/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6928 - accuracy: 0.5597
Epoch 4/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6926 - accuracy: 0.5597
Epoch 5/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6924 - accuracy: 0.5597
Epoch 6/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6922 - accuracy: 0.5597
Epoch 7/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6918 - accuracy: 0.5597
Epoch 8/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6916 - accuracy: 0.5597
Epoch 9/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6914 - accuracy: 0.5597
Epoch 10/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6910 - accuracy: 0.5597
Epoch 11/500
5/5 [==========

5/5 [==============================] - 0s 2ms/step - loss: 0.6862 - accuracy: 0.5597
Epoch 85/500
5/5 [==============================] - 0s 4ms/step - loss: 0.6862 - accuracy: 0.5597
Epoch 86/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6862 - accuracy: 0.5597
Epoch 87/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 88/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 89/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 90/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 91/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 92/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 93/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 94/500
5/5 [===============

5/5 [==============================] - 0s 3ms/step - loss: 0.6862 - accuracy: 0.5597
Epoch 167/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 168/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 169/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 170/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 171/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6862 - accuracy: 0.5597
Epoch 172/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 173/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 174/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 175/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 176/500
5/5 [=====

5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 249/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 250/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 251/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 252/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 253/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 254/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 255/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 256/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 257/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 258/500
5/5 [=====

5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 331/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6862 - accuracy: 0.5597
Epoch 332/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 333/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 334/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 335/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 336/500
5/5 [==============================] - ETA: 0s - loss: 0.6777 - accuracy: 0.59 - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 337/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 338/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 339/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 -

5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 413/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 414/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 415/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 416/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 417/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 418/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 419/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 420/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 421/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 422/500
5/5 [=====

5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 494/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 495/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 496/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 497/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 498/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597
Epoch 499/500
5/5 [==============================] - 0s 2ms/step - loss: 0.6861 - accuracy: 0.5597
Epoch 500/500
5/5 [==============================] - 0s 3ms/step - loss: 0.6860 - accuracy: 0.5597


In [20]:
y_pred =model.predict(x_test)

In [21]:
y_pred= y_pred.round()

In [22]:
y_test

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [23]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.6862 - accuracy: 0.5588


[0.686211347579956, 0.5588235259056091]

In [24]:
from sklearn.metrics import confusion_matrix, classification_report

In [25]:
print(confusion_matrix(y_test,y_pred))

[[ 0 15]
 [ 0 19]]


In [26]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.56      1.00      0.72        19

    accuracy                           0.56        34
   macro avg       0.28      0.50      0.36        34
weighted avg       0.31      0.56      0.40        34



C:\Users\admin\.conda\envs\deepl2\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\admin\.conda\envs\deepl2\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\admin\.conda\envs\deepl2\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
