In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
import keras
from keras.layers import Dense
from keras.models import Sequential

In [4]:
dataset=pd.read_csv('iris.csv',names=['Sepal_length','Sepal_width','Petal_length','Petal_width','Label'])

In [5]:
dataset

Sepal_length  Sepal_width  Petal_length  Petal_width           Label
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
x= dataset.iloc[:,0:4].values
y= dataset.iloc[:,4].values

In [7]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le= LabelEncoder()

In [11]:
y= le.fit_transform(y)

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
x_train.shape

(120, 4)

In [15]:
x_test.shape

(30, 4)

In [16]:
model= Sequential([
    Dense(10,activation='relu',input_shape=[4]),
    Dense(10,activation='relu'),
    Dense(3,activation='softmax')
])

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

In [30]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3590 - accuracy: 0.9250
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 0.3616 - accuracy: 0.8667
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3559 - accuracy: 0.9333
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.3561 - accuracy: 0.9167
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3514 - accuracy: 0.9333
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3573 - accuracy: 0.8917
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3495 - accuracy: 0.8833
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 0.3460 - accuracy: 0.9417
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3493 - accuracy: 0.8917
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3421 - accuracy: 0.9250
Epoch 11/100
4/4 [===========

4/4 [==============================] - 0s 3ms/step - loss: 0.2165 - accuracy: 0.9667
Epoch 85/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2161 - accuracy: 0.9583
Epoch 86/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2187 - accuracy: 0.9667
Epoch 87/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2137 - accuracy: 0.9583
Epoch 88/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2205 - accuracy: 0.9417
Epoch 89/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2140 - accuracy: 0.9583
Epoch 90/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2302 - accuracy: 0.9167
Epoch 91/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2219 - accuracy: 0.9417
Epoch 92/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2163 - accuracy: 0.9417
Epoch 93/100
4/4 [==============================] - 0s 3ms/step - loss: 0.2055 - accuracy: 0.9583
Epoch 94/100
4/4 [===============

In [31]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 197ms/step - loss: 0.1961 - accuracy: 1.0000


[0.19611606001853943, 1.0]

In [32]:
y_pred = model.predict(x_test)

In [33]:
y_pred.round()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [34]:
y_pred = np.argmax(y_pred,axis=1)

In [35]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [36]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [37]:
print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

